### ISSUE TITLE
Changes necessary to build and run

### ISSUE THREAD

**Issue by slimandslam** [jiemakel/snapper#7]
It required a number of changes to the package.json and bower.json files in order to get this to build and run under Centos 6.5.  The most notable was that it tries to install and use "LiveScript" which is now called "livescript".

**Comment by jiemakel** [comment]
I've now updated the dependencies (as well as fixed a couple of bugs).

**Comment by slimandslam** [comment]
Still does not build and run on CentOS 7 unless nodejs is upgraded from 0.10 to 0.12
Have you checked to see if it builds and runs on nodejs 0.10 ?

J

**Comment by jiemakel** [comment]
You're correct. I got it to build and run on 0.11 however, so set the package.json requirement to that.
